name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.9"

      - name: Download embeddable Python
        run: |
          $url = "https://www.python.org/ftp/python/3.11.9/python-3.11.9-embed-amd64.zip"
          $output = "$env:TEMP/python-embed.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath ./python -Force
          Remove-Item $output

      - name: Install dependencies
        run: |
          pip install .
          $pythonPath = (Get-Command python | Select-Object -First 1).Source
          $packagePath = "$pythonPath\..\Lib\site-packages"
          Copy-Item -Path $packagePath -Destination python\site-packages -Recurse
          Add-Content -Path python\python311._pth -Value "`nsite-packages"
          Add-Content -Path python\python311._pth -Value "site-packages/win32"
          Add-Content -Path python\python311._pth -Value "site-packages/win32/lib"

      - name: Compress files
        run: |
          Compress-Archive -Path . -DestinationPath manga-text-detection_${{ github.ref_name }}_windows_amd64.zip -CompressionLevel Optimal

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manga-text-detection_${{ github.ref_name }}_windows_amd64.zip
